version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      weekly-batch:
        patterns:
          - "*"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      weekly-batch:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/onc-node"
      - "/packages/onc-rpcbind-server"
      - "/packages/onc-rpcbind-client"
      - "/packages/onc-rpcbind-common"
      - "/packages/onc-xdr"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]