name: onc-rpcbind-client CI
on:
  push:
    branches: [main]
    paths:
      - "packages/**"
      - ".github/workflows/onc-rpcbind-client.yml"
      - ".github/workflows/module.yml"

permissions:
  id-token: write
  contents: read

jobs:
  module-flow:
    uses: ./.github/workflows/module.yml
    with:
      package-path: packages/onc-rpcbind-client
